src/api/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include
from rest_framework import routers, serializers, viewsets
from api.views import IssueViewSet, ProjectIssuesViewSet, ProjectTimelogsViewSet, ProjectViewSet, NotificationViewSet
from api.views import TimelogViewSet, UserViewSet, ProjectIssuesCommentsViewSet, ProjectIssuesTimelogsViewSet
from api.views import ProjectSprintsViewSet
from rest_framework_simplejwt.views import TokenRefreshView
from api.custom_jwt_auth import CustomTokenObtainPairView

from common.urls import project_pattern, project_pattern_optional, issue_pattern
app_name = 'api'

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'timelogs', TimelogViewSet, 'timelogs')
router.register(r'notifications', NotificationViewSet, 'notifications')
router.register(r'issues', IssueViewSet, 'issues')
router.register(r'projects', ProjectViewSet, 'project')
router.register(r'projects/' + project_pattern+r'timelogs', ProjectTimelogsViewSet, 'project_timelogs')
router.register(r'projects/' + project_pattern+r'issues', ProjectIssuesViewSet, 'project_issues')
router.register(r'projects/' + project_pattern+r'sprints', ProjectSprintsViewSet, 'project_sprints')
router.register(r'projects/' + project_pattern+r'issues/'+issue_pattern+r'comments',
                ProjectIssuesCommentsViewSet, 'project_issues_comments')
router.register(r'projects/' + project_pattern+r'issues/'+issue_pattern+r'timelogs',
                ProjectIssuesTimelogsViewSet, 'project_issues_timelogs')
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

src/archive/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url

from archive import views

app_name = 'archive'


urlpatterns = [
    url(r'^archive/?$', views.ArchivedIssuesView.as_view(), name='archive'),
]

src/common/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


from common import views

app_name = 'common'


project_pattern = r'(?P<project>[0-9a-zA-Z]{1,4})/'
project_pattern_optional = r'(?P<project>[0-9a-zA-Z]{1,4})?'
issue_pattern = r'(?P<issue>[0-9]+)/'
issue_pattern_optional = r'(?P<issue>[0-9]+)?/'

urlpatterns = [
    url(r'^', include('landing_page.urls')),
    url(r'^', include('user_management.urls')),
    url(r'^',
        include(([url(r'^filter_create/$', views.CreateFilterView.as_view(), name='create_filter'), ],
                 'common'))),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^invite/', include('invite_users.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^project/'+project_pattern, include('archive.urls')),
    url(r'^project/'+project_pattern, include('backlog.urls')),
    url(r'^project/'+project_pattern, include('olea.urls')),
    url(r'^project/'+project_pattern, include('sprint.urls')),
    url(r'^project/'+project_pattern+r'column/', include('kanbancol.urls')),
    url(r'^project/'+project_pattern+r'integration/', include('integration.urls')),
    url(r'^', include('issue.urls')),
    url(r'^project/'+project_pattern+r'tag/', include('tag.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^timelog/', include('timelog.urls')),
    url(r'^user/', include('user_profile.urls')),
    url(r'^', include('discussion.urls')),
    url(r'^media/.*', views.ShowProtectedFilesView.as_view()),
    url(r'^api/', include('api.urls', namespace='api')),
]


# enable the admin interface by request
if settings.ADMIN_ENABLED:
    urlpatterns.append(url(r'^admin/', admin.site.urls))

# this is needed to load the media files in the built-in django server
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/issue/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include

from issue import views
from timelog import views as tl_views
from gitintegration import views as repo_views
from common.urls import project_pattern
from issue.autocomplete import IssuePrioAutocompleteView,\
    IssueTypeAutocompleteView

app_name = 'issue'

issue_sqn_s_pattern = r'(?P<sqn_s>[0-9]+)'


urlpatterns = [
    url(r'^issue/', include([
        url(r'^$', views.IssueListAllView.as_view(), name='issue_list_all_view'),
        url(r'^prioac/?$', IssuePrioAutocompleteView.as_view(), name='prioac'),
        url(r'^typeac/?$', IssueTypeAutocompleteView.as_view(), name='typeac'),
    ])),
    url(r'^project/'+project_pattern+r'issue/', include([
        url(r'^create/?$', views.IssueCreateView.as_view(), name='create'),
        url(r'assigntome/?$', views.AssignIssueToMeView.as_view(), name='assigntome',),
        url(r'^rmfromme/?$', views.RemoveIssueFromMeView.as_view(), name='rmfromme',),
        url(r'^setkanbancol/?$', views.AddIssueToKanbancolView.as_view(), name='setkanbancol',),
        url(r'^archivecol/?$', views.ArchiveMultipleIssueView.as_view(), name='archivecol',),
        url(r'^archiveissue/?$', views.ArchiveSingleIssueView.as_view(), name='archiveissue',),
        url(r'^unarchiveissue/?$', views.UnArchiveSingleIssueView.as_view(), name='unarchiveissue',),
        url(r'^(?P<sqn_i>[0-9]+)/', include([
            url(r'^$', views.IssueDetailView.as_view(), name='detail'),
            url(r'^edit/?$', views.IssueEditView.as_view(), name='edit'),
            url(r'^delete/?$', views.IssueDeleteView.as_view(), name='delete'),
            url(r'^comment/(?P<pk_c>[0-9]+)/?$', views.IssueEditCommentView.as_view(), name='edit_comment'),
            url(r'^comment/(?P<pk_c>[0-9]+)/delete/?$', views.IssueDeleteCommentView.as_view(), name='delete_comment'),
            url(r'^attach/(?P<sqn_a>[0-9]+)/?$', views.AttachmentDownloadView.as_view(), name='download_attachment'),
            url(r'^attach/(?P<sqn_a>[0-9]+)/delete/?$', views.AttachmentDeleteView.as_view(), name='delete_attachment'),
            url(r'^log/?$', tl_views.TimelogCreateView.as_view(), name='log'),
            url(r'^punch/?$', tl_views.PunchView.as_view(), name='punch'),
            url(r'^logs/(?P<sqn_l>[0-9]+)/edit/?$', tl_views.TimelogEditView.as_view(), name='logedit'),
            url(r'^logs/(?P<sqn_l>[0-9]+)/delete/?$', tl_views.TimelogDeleteView.as_view(), name='logdelete'),
            url(r'diff/?$', repo_views.FileDiffView.as_view(), name='commit_diff'),
        ]))
    ]))
]

src/olea/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url

from olea import views

app_name = 'olea'


urlpatterns = [
    url(r'^processOlea/?$', views.ProcessOleaView.as_view(), name='processOlea'),
]

src/sprint/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url

from sprint import views

app_name = 'sprint'


sprint_sqn_s_pattern = r'(?P<sqn_s>[0-9]+)'

urlpatterns = [
    url(r'^$', views.SprintboardView.as_view(), name='sprintboard'),
    url(r'^newsprint/?$', views.NewSprintView.as_view(), name='newsprint'),
    url(r'^editsprint/'+sprint_sqn_s_pattern+r'/?$', views.SprintEditView.as_view(), name='editsprint'),
    # NOTE WARNING: this page is broken because of the errors described in the relative template
    #      the WHOLE PROJECT WILL BE DELETED!!! NOTE DON'T REACTIVATE WITHOUT FIX!!!!!!!!!!!!
    # url(r'^deletesprint/'+sprint_sqn_s_pattern+r'/?$', views.Sprint_Delete_View.as_view(), name='deletesprint'),
    url(r'toggletofromsprint/?$', views.ToggleIssueToFromSprintView.as_view(), name='assigntosprint',),
    url(r'^startsprint/'+sprint_sqn_s_pattern+r'/?$', views.StartSprintView.as_view(), name='startsprint'),
    url(r'^stopsprint/'+sprint_sqn_s_pattern+r'/?$', views.StopSprintView.as_view(), name='stopsprint'),
]

src/issue/templates/issue/issue_option_template.html
<!--
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
{% load i18n %}
<div class="dropdown" style=" display:inline-block;">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-option-vertical"></span></a>
	<ul class="dropdown-menu {% if "issue" in request.get_full_path %}dropdown-menu-right{% endif %}" role="menu">
		<li>
			<a href="{% url 'issue:detail' project=issue.project.name_short sqn_i=issue.number %}"><span class="glyphicon glyphicon-leaf"></span> Details </a>
		</li>
		<li>
			<a href="{% url 'issue:edit' project=issue.project.name_short sqn_i=issue.number %}"><span class="glyphicon glyphicon-pencil"></span> Edit issue </a>
		</li>
		<li>
			{% if request.user in issue.participant.all %}
				<form method="post" action="{% url 'discussion:mute' issue.project.name_short issue.number %}">
					{% csrf_token %}
					<input type="hidden" name="next" value={{request.get_full_path}} />
					<button type="submit" class="btn btn-link">
						<span class="glyphicon glyphicon-eye-close"></span> {% trans "Mute"%}
					</button>
				</form>
			{% else %}
				<form method="post" action="{% url 'discussion:follow' issue.project.name_short issue.number %}">
					{% csrf_token %}
					<input type="hidden" name="next" value={{request.get_full_path}} />
					<button type="submit" class="btn btn-link">
						<span class="glyphicon glyphicon-eye-open"></span> {% trans "Follow"%}
					</button>
				</form>
			{% endif %}
		</li>
		{% if issue.archived %}
			<li>
				<form  method="post" action="{% url 'issue:unarchiveissue' project=issue.project.name_short %}" >{% csrf_token %}
					<input type="hidden" name="next" value={{request.get_full_path}} />
					<input type="hidden" name="sqn_i" value= {{issue.number}} />
					<button type="submit" class="btn btn-link"><span class="glyphicon glyphicon-book"></span> {% trans "Unarchive"%}</button>
				</form>
			</li>
			<li>
				<a id="issue_delete_link_{{issue.number}}" href="{% url 'issue:delete' project=issue.project.name_short sqn_i=issue.number %}">
					<span class="glyphicon glyphicon-trash"></span> {% trans "Delete"%}
				</a>
			</li>
		{% else %}
			<li>
				{% if request.user in issue.assignee.all %}
					<form id="atm{{issue.number}}" method="post" action="{% url 'issue:rmfromme' project=issue.project.name_short %}" >{% csrf_token %}
						<input type="hidden" name="next" value={{request.get_full_path}} />
						<input type="hidden" name="sqn_i" value={{issue.number}} />
						<button type="submit" class="btn btn-link">
							<span class="glyphicon glyphicon-star"></span> Remove from me
						</button>
					</form>
				{% else %}
					<form id="atm{{issue.number}}" method="post" action="{% url 'issue:assigntome' project=issue.project.name_short %}" >{% csrf_token %}
						<input type="hidden" name="next" value={{request.get_full_path}} />
						<input type="hidden" name="sqn_i" value={{issue.number}} />
						<button type="submit" class="btn btn-link">
							<span class="glyphicon glyphicon-star-empty"></span> Assign to me
						</button>
					</form>
				{% endif %}
				<li>
					<li>
						<form id="punch{{issue.number}}"  method="post" action="{% url 'issue:punch' project=issue.project.name_short sqn_i=issue.number %}" >{% csrf_token %}
							<input type="hidden" name="next" value={{request.get_full_path}} />
							<button type="submit" class="btn btn-link">
								{% if request.user.punched_on.all.first.issue == issue %}
									<span class="glyphicon glyphicon-record" style="color:red"></span> Punch out
								{% else %}
									<span class="glyphicon glyphicon-record" title="Punch in"></span> Punch in
								{% endif %}
							</button>
						</form>
					</li>
					{% if not issue.sprint.is_active %}
						<li>
							<form  method="post" action="{% url 'issue:archiveissue' project=issue.project.name_short %}" >{% csrf_token %}
								<input type="hidden" name="next" value={{request.get_full_path}} />
								<input type="hidden" name="sqn_i" value= {{issue.number}} />
								<button type="submit" class="btn btn-link"><span class="glyphicon glyphicon-book"></span> {% trans "Archive"%}</button>
							</form>
						</li>
					{% endif %}
				{% endif %}
	</ul>
</div>