src/api/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include
from rest_framework import routers, serializers, viewsets
from api.views import IssueViewSet, ProjectIssuesViewSet, ProjectTimelogsViewSet, ProjectViewSet, NotificationViewSet
from api.views import TimelogViewSet, UserViewSet, ProjectIssuesCommentsViewSet, ProjectIssuesTimelogsViewSet
from api.views import ProjectSprintsViewSet
from rest_framework_simplejwt.views import TokenRefreshView
from api.custom_jwt_auth import CustomTokenObtainPairView

from common.urls import project_pattern, project_pattern_optional, issue_pattern
app_name = 'api'

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'timelogs', TimelogViewSet, 'timelogs')
router.register(r'notifications', NotificationViewSet, 'notifications')
router.register(r'issues', IssueViewSet, 'issues')
router.register(r'projects', ProjectViewSet, 'project')
router.register(r'projects/' + project_pattern+r'timelogs', ProjectTimelogsViewSet, 'project_timelogs')
router.register(r'projects/' + project_pattern+r'issues', ProjectIssuesViewSet, 'project_issues')
router.register(r'projects/' + project_pattern+r'sprints', ProjectSprintsViewSet, 'project_sprints')
router.register(r'projects/' + project_pattern+r'issues/'+issue_pattern+r'comments',
                ProjectIssuesCommentsViewSet, 'project_issues_comments')
router.register(r'projects/' + project_pattern+r'issues/'+issue_pattern+r'timelogs',
                ProjectIssuesTimelogsViewSet, 'project_issues_timelogs')
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

src/issue/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include

from issue import views
from timelog import views as tl_views
from gitintegration import views as repo_views
from common.urls import project_pattern
from issue.autocomplete import IssuePrioAutocompleteView,\
    IssueTypeAutocompleteView

app_name = 'issue'

issue_sqn_s_pattern = r'(?P<sqn_s>[0-9]+)'


urlpatterns = [
    url(r'^issue/', include([
        url(r'^$', views.IssueListAllView.as_view(), name='issue_list_all_view'),
        url(r'^prioac/?$', IssuePrioAutocompleteView.as_view(), name='prioac'),
        url(r'^typeac/?$', IssueTypeAutocompleteView.as_view(), name='typeac'),
    ])),
    url(r'^project/'+project_pattern+r'issue/', include([
        url(r'^create/?$', views.IssueCreateView.as_view(), name='create'),
        url(r'assigntome/?$', views.AssignIssueToMeView.as_view(), name='assigntome',),
        url(r'^rmfromme/?$', views.RemoveIssueFromMeView.as_view(), name='rmfromme',),
        url(r'^setkanbancol/?$', views.AddIssueToKanbancolView.as_view(), name='setkanbancol',),
        url(r'^archivecol/?$', views.ArchiveMultipleIssueView.as_view(), name='archivecol',),
        url(r'^archiveissue/?$', views.ArchiveSingleIssueView.as_view(), name='archiveissue',),
        url(r'^unarchiveissue/?$', views.UnArchiveSingleIssueView.as_view(), name='unarchiveissue',),
        url(r'^(?P<sqn_i>[0-9]+)/', include([
            url(r'^$', views.IssueDetailView.as_view(), name='detail'),
            url(r'^edit/?$', views.IssueEditView.as_view(), name='edit'),
            url(r'^delete/?$', views.IssueDeleteView.as_view(), name='delete'),
            url(r'^comment/(?P<pk_c>[0-9]+)/?$', views.IssueEditCommentView.as_view(), name='edit_comment'),
            url(r'^comment/(?P<pk_c>[0-9]+)/delete/?$', views.IssueDeleteCommentView.as_view(), name='delete_comment'),
            url(r'^attach/(?P<sqn_a>[0-9]+)/?$', views.AttachmentDownloadView.as_view(), name='download_attachment'),
            url(r'^attach/(?P<sqn_a>[0-9]+)/delete/?$', views.AttachmentDeleteView.as_view(), name='delete_attachment'),
            url(r'^log/?$', tl_views.TimelogCreateView.as_view(), name='log'),
            url(r'^punch/?$', tl_views.PunchView.as_view(), name='punch'),
            url(r'^logs/(?P<sqn_l>[0-9]+)/edit/?$', tl_views.TimelogEditView.as_view(), name='logedit'),
            url(r'^logs/(?P<sqn_l>[0-9]+)/delete/?$', tl_views.TimelogDeleteView.as_view(), name='logdelete'),
            url(r'diff/?$', repo_views.FileDiffView.as_view(), name='commit_diff'),
        ]))
    ]))
]

src/timelog/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url
from timelog import views, json
app_name = 'timelog'

urlpatterns = [
    url(r'^$', views.TimelogLoginfoPerUserView.as_view(), name='loginfo'),
    # url(r'^lastseven/$', views.Timelog_chartjs.as_view(), name='last7days'),
    url(r'^lastweek/$', views.TimelogD3View.as_view(), name='d3'),
    url(r'^activity/$', views.TimelogGetActivityDataView.as_view(), name='activity'),
    url(r'^logs/$', views.TimelogArchivView.as_view(), name='archiv'),
    url(r'^api/last_7_days/?$', json.d3_json_last_7_days, name='api_last_7_days'),
    url(r'^api/activity/?$', json.d3_json_activity, name='api_activity'),
    url(r'^api/project_activity/?$', json.get_activity_data_for_project, name='api_project_activity'),
    url(r'^api/(?P<date>[0-9]+)?/?', json.d3_json_logs_specific_day, name='api_logs_on_date'),
]

src/timelog/forms.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.forms import Field, ModelForm, ValidationError

from datetime import timedelta
import re

from .models import Timelog
from issue.models import Issue

from django.utils.translation import ugettext_lazy as _
from timelog.widgets import DurationWidget
from common.widgets import LocalizedDateTimePickerInput

duration_field_help_text = _('e.g. 1d2h10m')


class TimelogCreateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(TimelogCreateForm, self).__init__(*args, **kwargs)
        self.fields['time'] = DurationField(help_text=duration_field_help_text)

    class Meta:
        model = Timelog
        fields = ('time', 'created_at')
        widgets = {
            # Use localization and bootstrap 3
            'created_at': LocalizedDateTimePickerInput(attrs={'id': "created_at"}),
        }


class TimelogCreateForm2(ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(TimelogCreateForm2, self).__init__(*args, **kwargs)
        self.fields['time'] = DurationField(help_text=duration_field_help_text)
        self.fields['issue'].queryset = Issue.objects.filter(assignee=user, archived=False)

    class Meta:
        model = Timelog
        fields = ('time', 'created_at', 'issue')
        widgets = {
            # Use localization and bootstrap 3
            'created_at': LocalizedDateTimePickerInput(attrs={'id': "created_at"}),
        }


class TimelogEditForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(TimelogEditForm, self).__init__(*args, **kwargs)
        self.fields['time'] = DurationField()

    class Meta:
        model = Timelog
        fields = ['time', 'created_at']
        widgets = {
            # Use localization and bootstrap 3
            'created_at': LocalizedDateTimePickerInput(attrs={'id': "created_at"}),
        }


class DurationField(Field):
    widget = DurationWidget

    def __init__(self, max_length=None, min_length=None, strip=True, *args, **kwargs):
        super(DurationField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        regex = re.compile(r'((?P<days>\d+?)d\s?)?((?P<hours>\d+?)h\s?)?((?P<minutes>\d+?)m)?')

        def parse_time(time_str):
            if not time_str:
                return None
            parts = regex.fullmatch(time_str)
            if not parts:
                raise ValidationError(_('Invalid time syntax, try e.g "3h5m" or "1h 20m" or "2d15m"'))
            parts = parts.groupdict()
            time_params = {}
            for name, param in parts.items():
                if param:
                    time_params[name] = int(param)
            return timedelta(**time_params)
        return parse_time(value)

    def widget_attrs(self, widget):
        attrs = super(DurationField, self).widget_attrs(widget)

src/timelog/templates/timelog/timelog_archiv.html
<!--
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
{% extends "_base.html" %}
{% load i18n %}
{% load filter %}

{% block title %}{% trans "Timelog Archiv" %}{% endblock title %}

{% block content %}
{% include "timelog/timelog_navigation_bar.html" %}

<p></p>
<div class="row">
	<div class="col-md-12">
		<ul class="list-group">
			<li class ="list-group-item list-first">
				<div class="row">
					<div class="col-xs-5">{%trans "Time" %}</div>
					<div class="col-xs-5">{%trans "Issue" %}</div>
				</div>
			</li>
			{% for l in logs %}
				<li id="log_{{forloop.counter}}" class ="list-group-item">
					<div class="row">
						<div class="col-xs-5">{{ l.time|duration }}
							<br><small> {{ l.created_at }} </small>
						</div>
						<div class="col-xs-5">
							{% if request.user in l.issue.project.get_members %}
								<a href="{% url 'issue:detail' project=l.issue.project.name_short sqn_i=l.issue.number %}" title="{{ l.issue.title }}">
								{{ l.issue.title|issue_title }}</a>
							{% else %}
								{{ l.issue.title|issue_title }}
							{% endif %}
						</div>
						<div class="col-xs-1">
							<a id="log_edit_link_{{forloop.counter}}" href="{% url 'issue:logedit' project=l.issue.project.name_short sqn_i=l.issue.number sqn_l=l.number %}?next={{ request.get_full_path }}">
								<span class="glyphicon glyphicon-pencil"></span>
							</a>
						</div>
						<div class="col-xs-1">
							<a id="log_delete_link_{{forloop.counter}}" href="{% url 'issue:logdelete' project=l.issue.project.name_short sqn_i=l.issue.number sqn_l=l.number  %}?next={{ request.get_full_path}}">
								<span class="glyphicon glyphicon-remove"></span>
							</a>
						</div>
					</div>
				</li>
			{% endfor %}
		</ul>
		<div class="pagination">
			<span class="step-links">
				{% if logs.has_previous %}
					<a href="?page={{ logs.previous_page_number }}">previous</a>
				{% endif %}

				<span class="current">
					Page {{ logs.number }} of {{ logs.paginator.num_pages }}.
				</span>

				{% if logs.has_next %}
					<a href="?page={{ logs.next_page_number }}">next</a>
				{% endif %}
			</span>
		</div>
	</div>
</div>
{% endblock content %}

src/timelog/templates/timelog/timelog_list_peruser.html
<!--
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
{% extends "_base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load filter %}

{% block title %}{% trans "Timelog" %}{% endblock title %}

{% block content %}
{% trans "overview" as viewpoint %}
{% include "timelog/timelog_navigation_bar.html" %}

<p></p>
<div class="row">
	<div class="col-md-5">
		<div class="panel panel-default">
			<div class="panel-heading">{% trans "Log Time" %}</div>
			<div class="panel-body">
				<form method="POST" class="post-form">{% csrf_token %}
				{% bootstrap_form form %}
				{% buttons %}
					<button type="submit" class="save btn btn-default" id="id_submit_create">
						{% trans "Save" %}
					</button>
				{% endbuttons %}
				</form>
			</div>
		</div>
	</div>
	<div class="col-md-7">
		<div class="panel panel-default">
			<div class ="panel-heading">
				<div class="row">
					<div class="col-xs-5">{%trans "Time" %}</div>
					<div class="col-xs-5">{%trans "Issue" %}</div>
					<div class="col-xs-2"></div>
				</div>
			</div>
			<ul class="list-group">
			{% for l in logs %}
				<li id="log_{{forloop.counter}}" class ="list-group-item">
					<div class="row">
						<div class="col-xs-5">{{ l.time|duration }}
							<br><small> {{ l.created_at }} </small>
						</div>
						<div class="col-xs-5">
							{% if request.user in l.issue.project.get_members %}
								<a href="{% url 'issue:detail' project=l.issue.project.name_short sqn_i=l.issue.number %}" title="{{ l.issue.title }}">
								{{ l.issue.title|issue_title }}</a>
							{% else %}
								{{ l.issue.title|issue_title }}
							{% endif %}
						</div>
						<div class="col-xs-1">
							<a id="log_edit_link_{{forloop.counter}}" href="{% url 'issue:logedit' project=l.issue.project.name_short sqn_i=l.issue.number sqn_l=l.number %}">
								<span class="glyphicon glyphicon-pencil"></span>
							</a>
						</div>
						<div class="col-xs-1">
							<a id="log_delete_link_{{forloop.counter}}" href="{% url 'issue:logdelete' project=l.issue.project.name_short sqn_i=l.issue.number sqn_l=l.number  %}">
								<span class="glyphicon glyphicon-remove"></span>
							</a>
						</div>
					</div>
				</li>
			{% endfor %}
			<li class ="list-group-item">
				<a href="{% url 'timelog:archiv' %}?page=2">{% trans "Timelog Archiv (load more)" %}</a>
			</li>
			</ul>
		</div>
	</div>
</div>
{% endblock content %}

{% block extra_script %}
	{{ form.media }}
{% endblock %}

src/timelog/templates/timelog/timelog_navigation_bar.html
<!--
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<ul class="nav nav-tabs">
	<li class="{% if viewpoint == 'overview' %}active{% endif %}"><a href="{% url 'timelog:loginfo' %}">Overview</a></li>
	<li class="{% if viewpoint == 'heatmap' %}active{% endif %}"><a href="{% url 'timelog:activity' %}">Activity</a></li>
	<li class="{% if viewpoint == 'lastseven' %}active{% endif %}"><a href="{% url 'timelog:d3' %}">Last Week</a></li>
</ul>