src/api/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include
from rest_framework import routers, serializers, viewsets
from api.views import IssueViewSet, ProjectIssuesViewSet, ProjectTimelogsViewSet, ProjectViewSet, NotificationViewSet
from api.views import TimelogViewSet, UserViewSet, ProjectIssuesCommentsViewSet, ProjectIssuesTimelogsViewSet
from api.views import ProjectSprintsViewSet
from rest_framework_simplejwt.views import TokenRefreshView
from api.custom_jwt_auth import CustomTokenObtainPairView

from common.urls import project_pattern, project_pattern_optional, issue_pattern
app_name = 'api'

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'timelogs', TimelogViewSet, 'timelogs')
router.register(r'notifications', NotificationViewSet, 'notifications')
router.register(r'issues', IssueViewSet, 'issues')
router.register(r'projects', ProjectViewSet, 'project')
router.register(r'projects/' + project_pattern+r'timelogs', ProjectTimelogsViewSet, 'project_timelogs')
router.register(r'projects/' + project_pattern+r'issues', ProjectIssuesViewSet, 'project_issues')
router.register(r'projects/' + project_pattern+r'sprints', ProjectSprintsViewSet, 'project_sprints')
router.register(r'projects/' + project_pattern+r'issues/'+issue_pattern+r'comments',
                ProjectIssuesCommentsViewSet, 'project_issues_comments')
router.register(r'projects/' + project_pattern+r'issues/'+issue_pattern+r'timelogs',
                ProjectIssuesTimelogsViewSet, 'project_issues_timelogs')
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

src/archive/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url

from archive import views

app_name = 'archive'


urlpatterns = [
    url(r'^archive/?$', views.ArchivedIssuesView.as_view(), name='archive'),
]

src/backlog/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url

from backlog import views

app_name = 'backlog'


sprint_sqn_s_pattern = r'(?P<sqn_s>[0-9]+)'

urlpatterns = [
    url(r'backlog/?$', views.BacklogListView.as_view(), name='backlog'),
    url(r'^backlog/'+sprint_sqn_s_pattern+r'/?$', views.BacklogListView.as_view(), name='backlog'),
]

src/issue/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include

from issue import views
from timelog import views as tl_views
from gitintegration import views as repo_views
from common.urls import project_pattern
from issue.autocomplete import IssuePrioAutocompleteView,\
    IssueTypeAutocompleteView

app_name = 'issue'

issue_sqn_s_pattern = r'(?P<sqn_s>[0-9]+)'


urlpatterns = [
    url(r'^issue/', include([
        url(r'^$', views.IssueListAllView.as_view(), name='issue_list_all_view'),
        url(r'^prioac/?$', IssuePrioAutocompleteView.as_view(), name='prioac'),
        url(r'^typeac/?$', IssueTypeAutocompleteView.as_view(), name='typeac'),
    ])),
    url(r'^project/'+project_pattern+r'issue/', include([
        url(r'^create/?$', views.IssueCreateView.as_view(), name='create'),
        url(r'assigntome/?$', views.AssignIssueToMeView.as_view(), name='assigntome',),
        url(r'^rmfromme/?$', views.RemoveIssueFromMeView.as_view(), name='rmfromme',),
        url(r'^setkanbancol/?$', views.AddIssueToKanbancolView.as_view(), name='setkanbancol',),
        url(r'^archivecol/?$', views.ArchiveMultipleIssueView.as_view(), name='archivecol',),
        url(r'^archiveissue/?$', views.ArchiveSingleIssueView.as_view(), name='archiveissue',),
        url(r'^unarchiveissue/?$', views.UnArchiveSingleIssueView.as_view(), name='unarchiveissue',),
        url(r'^(?P<sqn_i>[0-9]+)/', include([
            url(r'^$', views.IssueDetailView.as_view(), name='detail'),
            url(r'^edit/?$', views.IssueEditView.as_view(), name='edit'),
            url(r'^delete/?$', views.IssueDeleteView.as_view(), name='delete'),
            url(r'^comment/(?P<pk_c>[0-9]+)/?$', views.IssueEditCommentView.as_view(), name='edit_comment'),
            url(r'^comment/(?P<pk_c>[0-9]+)/delete/?$', views.IssueDeleteCommentView.as_view(), name='delete_comment'),
            url(r'^attach/(?P<sqn_a>[0-9]+)/?$', views.AttachmentDownloadView.as_view(), name='download_attachment'),
            url(r'^attach/(?P<sqn_a>[0-9]+)/delete/?$', views.AttachmentDeleteView.as_view(), name='delete_attachment'),
            url(r'^log/?$', tl_views.TimelogCreateView.as_view(), name='log'),
            url(r'^punch/?$', tl_views.PunchView.as_view(), name='punch'),
            url(r'^logs/(?P<sqn_l>[0-9]+)/edit/?$', tl_views.TimelogEditView.as_view(), name='logedit'),
            url(r'^logs/(?P<sqn_l>[0-9]+)/delete/?$', tl_views.TimelogDeleteView.as_view(), name='logdelete'),
            url(r'diff/?$', repo_views.FileDiffView.as_view(), name='commit_diff'),
        ]))
    ]))
]

src/sprint/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url

from sprint import views

app_name = 'sprint'


sprint_sqn_s_pattern = r'(?P<sqn_s>[0-9]+)'

urlpatterns = [
    url(r'^$', views.SprintboardView.as_view(), name='sprintboard'),
    url(r'^newsprint/?$', views.NewSprintView.as_view(), name='newsprint'),
    url(r'^editsprint/'+sprint_sqn_s_pattern+r'/?$', views.SprintEditView.as_view(), name='editsprint'),
    # NOTE WARNING: this page is broken because of the errors described in the relative template
    #      the WHOLE PROJECT WILL BE DELETED!!! NOTE DON'T REACTIVATE WITHOUT FIX!!!!!!!!!!!!
    # url(r'^deletesprint/'+sprint_sqn_s_pattern+r'/?$', views.Sprint_Delete_View.as_view(), name='deletesprint'),
    url(r'toggletofromsprint/?$', views.ToggleIssueToFromSprintView.as_view(), name='assigntosprint',),
    url(r'^startsprint/'+sprint_sqn_s_pattern+r'/?$', views.StartSprintView.as_view(), name='startsprint'),
    url(r'^stopsprint/'+sprint_sqn_s_pattern+r'/?$', views.StopSprintView.as_view(), name='stopsprint'),
]

src/backlog/templates/backlog/backlog_issue_template.html
<!--
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
{% load i18n %}
{% load cache %}
{% cache 86400 backlog_issue_template issue.project.name_short issue.number request.user.username %}
<tr id="{% if issue.sprint %}sprint{% else %}backlog{% endif %}_issue_{{issue.number}}" class="backlog-issue">
	<td style="white-space: nowrap;" title={{issue.type}}>
		<div class="issue-type text-muted {{issue.type|lower}}">
			{{ issue.type|slice:":1" }}
		</div>
		{% include "issue/issue_info_template.html" %}
	{% if view.get_sqn_s != -1 %}
		<td style="padding-left: 0px">
		<div class="pull-right">
				<form style="display:inline-block" id="ats{{issue.number}}" method="post" action="{% url 'sprint:assigntosprint' project=project.name_short %}" >{% csrf_token %}
					<input type="hidden" name="sqn_i" value={{issue.number}} />
					<button style="padding:0px" type="submit" class="btn btn-link">
						{% if issue.sprint %}
							<span class="glyphicon glyphicon-minus" title="{% trans "Remove from sprint" %}"></span>
						{% else %}
							<span class="glyphicon glyphicon-plus" title="{% trans "Add to sprint" %}"></span>
						{% endif %}
					</button>
				</form>
		</div>
		</td>
	{% endif %}
</tr>
{% endcache %}

src/backlog/templates/backlog/backlog_list.html
<!--
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
{% extends "_base.html" %}
{% load static %}
{% load i18n %}
{% load filter %}

{% block title %}{% trans "Backlog" %}{% endblock title %}

{% block content %}
{% trans "backlog" as viewpoint %}
{% include "project/project_navigation_bar.html" %}
<div class="row">
    <div class="col-md-12 olea-container">
        <div class="olea-flex-element">
		    {% include "olea/olea-bar.html" %}
		</div>
		<a class="btn btn-default olea-element" href="{% url 'sprint:newsprint' project=project.name_short %}"><span class="glyphicon glyphicon-plus"></span> {% trans "New sprint" %}</a>
		<form>
			<input type="text" id="text-filter" onkeyup="filter_issues('backlog-issue')" placeholder="Filter issues" class="form-control olea-element">
		</form>
		
		{% if request.GET.myissues == 'true' %}
			<a class="btn btn-default active olea-element" href="{{ request.path }}{% query_string request.META.QUERY_STRING myissues-'true'%}">{% trans "My issues" %}</a>
		{% else %}
			<a class="btn btn-default olea-element" href="{{ request.path }}{% query_string request.META.QUERY_STRING myissues+'true'%}">{% trans "My issues" %}</a>
		{% endif %}
		<div class="olea-element">
		    {% include "orderby.html" %}
		</div>
	</div>
</div>
<p></p>
<div class="row">
	<div class="col-md-{% if view.get_sqn_s != -1 %}6{% else %}12{% endif %}">
		<div class="panel panel-default" id="backlog_backlog">
			<div class="panel-heading">
				<span class="backlog-nondropdown">{% trans "Backlog" %} <span title="{% trans "Remaining issues" %}">({{ view.get_backlog_issues|length }})</span></span>
				<div class="btn-group pull-right">
					<a class="btn btn-default" href="{% url 'issue:create' project=project.name_short %}"><span class="glyphicon glyphicon-plus"></span> {% trans "New issue" %}</a>
				</div>
			</div>
			<table class="table">
				{% for issue in view.get_backlog_issues %}
					{% include "backlog/backlog_issue_template.html" %}
				{% empty %}
					<tr><td>{% trans "Congratulations! Your backlog is empty." %}</td></tr>
				{% endfor %}
			</table>
			<div class="panel-footer"><a href="{% url 'archive:archive' project=project.name_short %}" title="{% trans "Past issues" %}"><span class="glyphicon glyphicon-book"></span> {% trans "Archive" %}</a></div>
		</div>
	</div>

	{% if view.get_sqn_s != -1 %}
	<div class="col-md-6">
		<div class="panel panel-default" id="backlog_sprint">
			<div class="panel-heading clearfix" style="{% if view.is_old_sprint %} color: red{% endif %}">
				<div class="dropdown dropdown-sprints">
					{% if project.sprint.unstopped.all|length > 1 %}
						<button class="dropdown-toggle dropdown-toggle-sprints" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
							{% trans "Sprint" %} {{view.get_sqn_s}} <span  title="{% trans "Issues in this sprint" %}">({{ view.get_sprint_issues|length }})</span>
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
							{% for sprint in project.sprint.get_current_sprints %}
								<li>
									<a href="{% url 'backlog:backlog' project=project.name_short sqn_s=sprint.seqnum%}">Sprint {{sprint.seqnum}} (running)</a>
								</li>
							{% endfor %}
							{% for sprint in project.sprint.get_new_sprints %}
								<li>
									<a href="{% url 'backlog:backlog' project=project.name_short sqn_s=sprint.seqnum%}">Sprint {{sprint.seqnum}}</a>
								</li>
							{% endfor %}
						</ul>
					{% else %}
						<span class="backlog-nondropdown">{% trans "Sprint" %} {{view.get_sqn_s}} <span  title="{% trans "Issues in this sprint" %}">({{ view.get_sprint_issues|length }})</span></span>
					{% endif %}
					{% if storypoints_total %}
					<span class="story-points" title="{% trans "Total amount of storypoints in this sprint" %}">{{ storypoints_total }}</span>
					{% endif %}
				</div>
				<div class="btn-group pull-right">
					{% if not view.is_old_sprint %}
						{% if view.is_sprint_current %}
							{% if view.get_sprint_issues_left.all %}
					<a class="btn btn-default" href="{% url 'sprint:stopsprint' project=project.name_short sqn_s=view.get_sqn_s %}" title="{% trans "Stop sprint" %}"><span class="glyphicon glyphicon-stop"></span> {% trans "Stop" %}</a>
							{% else %}
						<form class="btn-group" method="post" action="{% url 'sprint:stopsprint' project=project.name_short sqn_s=view.get_sqn_s %}" >{% csrf_token %}
							<button type="submit" style="border-bottom-left-radius: 4px; border-top-left-radius: 4px" class="btn btn-default" id="stopsprint">
								<span class="glyphicon glyphicon-stop"></span> {% trans "Stop" %}
							</button>
						</form>
							{% endif %}
						{% else %}
					<form class="btn-group" method="post" action="{% url 'sprint:startsprint' project=project.name_short sqn_s=view.get_sqn_s %}" >{% csrf_token %}
						<button type="submit" style="border-bottom-left-radius: 4px; border-top-left-radius: 4px" class="btn btn-default" id="startsprint">
							<span class="glyphicon glyphicon-play"></span> {% trans "Start" %}
						</button>
					</form>
					<form class="btn-group" method="post" action="{% url 'sprint:stopsprint' project=project.name_short sqn_s=view.get_sqn_s %}" >{% csrf_token %}
						<button type="submit" class="btn btn-default" id="stopsprint">
							<span class="glyphicon glyphicon-minus"></span> {% trans "Remove" %}
						</button>
					</form>
					{% endif %}
					<a class="btn btn-default" href="{% url 'sprint:editsprint' project=project.name_short sqn_s=view.get_sqn_s %}" title="{% trans "Edit sprint" %}"><span class="glyphicon glyphicon-pencil"></span> {% trans "Edit" %}</a>
					{% else %}
						{% trans "Finished sprint" %}
					{% endif %}
				</div>
			</div>

			{% if view.get_sprint_issues.all %}
				<table class="table">
					{% if storypoints %}
						<tr>
						<td colspan="5">
						<b>{% trans "Storypoints:" %}</b>
							{% for item in storypoints %}
								{{item.0}}: {{item.1}} {% if not forloop.last %} / {% endif %}
							{% endfor %}
						</td>
						</tr>
					{% endif %}
					{% for issue in view.get_sprint_issues %}
						{% include "backlog/backlog_issue_template.html" %}
					{% endfor %}
				</table>
			{% else %}
				<div class="panel-body">{% trans "No issues in this sprint." %}</div>
			{% endif %}
			</div>
		</div>
	{% endif %}
	</div>
{% endblock content %}

{% block extra_script %}
<script type="text/javascript" src="{% static 'js/filter-issues.js' %}"></script>
{% endblock extra_script %}