src/api/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include
from rest_framework import routers, serializers, viewsets
from api.views import IssueViewSet, ProjectIssuesViewSet, ProjectTimelogsViewSet, ProjectViewSet, NotificationViewSet
from api.views import TimelogViewSet, UserViewSet, ProjectIssuesCommentsViewSet, ProjectIssuesTimelogsViewSet
from api.views import ProjectSprintsViewSet
from rest_framework_simplejwt.views import TokenRefreshView
from api.custom_jwt_auth import CustomTokenObtainPairView

from common.urls import project_pattern, project_pattern_optional, issue_pattern
app_name = 'api'

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'timelogs', TimelogViewSet, 'timelogs')
router.register(r'notifications', NotificationViewSet, 'notifications')
router.register(r'issues', IssueViewSet, 'issues')
router.register(r'projects', ProjectViewSet, 'project')
router.register(r'projects/' + project_pattern+r'timelogs', ProjectTimelogsViewSet, 'project_timelogs')
router.register(r'projects/' + project_pattern+r'issues', ProjectIssuesViewSet, 'project_issues')
router.register(r'projects/' + project_pattern+r'sprints', ProjectSprintsViewSet, 'project_sprints')
router.register(r'projects/' + project_pattern+r'issues/'+issue_pattern+r'comments',
                ProjectIssuesCommentsViewSet, 'project_issues_comments')
router.register(r'projects/' + project_pattern+r'issues/'+issue_pattern+r'timelogs',
                ProjectIssuesTimelogsViewSet, 'project_issues_timelogs')
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

src/issue/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include

from issue import views
from timelog import views as tl_views
from gitintegration import views as repo_views
from common.urls import project_pattern
from issue.autocomplete import IssuePrioAutocompleteView,\
    IssueTypeAutocompleteView

app_name = 'issue'

issue_sqn_s_pattern = r'(?P<sqn_s>[0-9]+)'


urlpatterns = [
    url(r'^issue/', include([
        url(r'^$', views.IssueListAllView.as_view(), name='issue_list_all_view'),
        url(r'^prioac/?$', IssuePrioAutocompleteView.as_view(), name='prioac'),
        url(r'^typeac/?$', IssueTypeAutocompleteView.as_view(), name='typeac'),
    ])),
    url(r'^project/'+project_pattern+r'issue/', include([
        url(r'^create/?$', views.IssueCreateView.as_view(), name='create'),
        url(r'assigntome/?$', views.AssignIssueToMeView.as_view(), name='assigntome',),
        url(r'^rmfromme/?$', views.RemoveIssueFromMeView.as_view(), name='rmfromme',),
        url(r'^setkanbancol/?$', views.AddIssueToKanbancolView.as_view(), name='setkanbancol',),
        url(r'^archivecol/?$', views.ArchiveMultipleIssueView.as_view(), name='archivecol',),
        url(r'^archiveissue/?$', views.ArchiveSingleIssueView.as_view(), name='archiveissue',),
        url(r'^unarchiveissue/?$', views.UnArchiveSingleIssueView.as_view(), name='unarchiveissue',),
        url(r'^(?P<sqn_i>[0-9]+)/', include([
            url(r'^$', views.IssueDetailView.as_view(), name='detail'),
            url(r'^edit/?$', views.IssueEditView.as_view(), name='edit'),
            url(r'^delete/?$', views.IssueDeleteView.as_view(), name='delete'),
            url(r'^comment/(?P<pk_c>[0-9]+)/?$', views.IssueEditCommentView.as_view(), name='edit_comment'),
            url(r'^comment/(?P<pk_c>[0-9]+)/delete/?$', views.IssueDeleteCommentView.as_view(), name='delete_comment'),
            url(r'^attach/(?P<sqn_a>[0-9]+)/?$', views.AttachmentDownloadView.as_view(), name='download_attachment'),
            url(r'^attach/(?P<sqn_a>[0-9]+)/delete/?$', views.AttachmentDeleteView.as_view(), name='delete_attachment'),
            url(r'^log/?$', tl_views.TimelogCreateView.as_view(), name='log'),
            url(r'^punch/?$', tl_views.PunchView.as_view(), name='punch'),
            url(r'^logs/(?P<sqn_l>[0-9]+)/edit/?$', tl_views.TimelogEditView.as_view(), name='logedit'),
            url(r'^logs/(?P<sqn_l>[0-9]+)/delete/?$', tl_views.TimelogDeleteView.as_view(), name='logdelete'),
            url(r'diff/?$', repo_views.FileDiffView.as_view(), name='commit_diff'),
        ]))
    ]))
]

src/project/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from project import views
from search import views as se_views
from common.urls import project_pattern, project_pattern_optional, issue_pattern_optional
from .autocomplete import *

app_name = 'project'

urlpatterns = [
    url(r'^$', views.ProjectListAllView.as_view(), name='list'),
    url(r'^create/?$', views.ProjectCreateView.as_view(), name='create'),
    url(r'^userac/?'+project_pattern_optional+r'/?$', UserAutocompleteView.as_view(), name='userac'),
    url(r'^issueac/'+project_pattern+issue_pattern_optional+r'?$', IssueAutocompleteView.as_view(), name='issueac'),
    url(r'^tagac/'+project_pattern_optional+r'/?$', TagAutocompleteView.as_view(), name='tagac'),
    url(r'^kanbanac/'+project_pattern_optional+r'/?$', KanbanAutocompleteView.as_view(), name='kanbanac'),
    url(project_pattern, include([
        url(r'^detail/?$', views.ProjectDetailView.as_view(), name='detail'),
        url(r'^timelog/?$', views.ProjectDetailTimelogView.as_view(), name='timelog'),
        url(r'^timelog/(?P<username>[a-zA-Z0-9_+\.-]+)/?$',
            views.ProjectUserTimelogView.as_view(),
            name='usertimelog'),
        url(r'^edit/?$', views.ProjectEditView.as_view(), name='edit'),
        url(r'^delete/?$', views.ProjectDeleteView.as_view(), name='delete'),
        url(r'^filter/?$', se_views.ProjectFilterView.as_view(), name='search'),
        url(r'^repository/', include('gitintegration.urls')),
        url(r'^leave/', views.LeaveProjectView.as_view(), name='leave'),
    ]))
]

src/user_profile/urls.py
"""
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
from django.conf.urls import url, include
from user_profile import views
from common.views import BreadcrumbView


app_name = 'user_profile'

urlpatterns = [
    url(r'^$', BreadcrumbView.as_view(breadcrumb="Profile")),
    url(r'^(?P<username>[a-zA-Z0-9_+\.-]+)/', include([
        url(r'^$', views.ShowProfilePageView.as_view(), name='user_profile_page'),
        url(r'^edit/?$', views.EditProfilePageView.as_view(), name='edit_profile'),
        url(r'^notify/?$', views.ToggleNotificationView.as_view(), name='toggle_notification'),
    ]))
]

src/user_profile/templates/user_profile/edit_user_profile.html
<!--
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
{% extends "_base.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% block title %}{% trans "Edit profile: " %}{{ user.username }}{% endblock title %}

{% block content %}
<h1>{% trans "Edit" %} {% if user.get_full_name and user.get_full_name.strip %}{{ user.get_full_name }}{% else %}{{ user.username }}{% endif %}:</h1>
<form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
	{% bootstrap_form forms.userChange %}
	{% bootstrap_form forms.passwordChange %}
	{% buttons %}
		<button type="submit" class="btn btn-default">
			{% trans "Save" %}
		</button>
	{% endbuttons %}
</form>
{% endblock content %}

src/user_profile/templates/user_profile/user_profile_page.html
<!--
Iguana (c) by Marc Ammon, Moritz Fickenscher, Lukas Fridolin, Michael Gunselmann, Katrin Raab, Christian Strate

Iguana is licensed under BSD-2-Clause License.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
{% extends "_base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Profile: " %}{{ user.username }}{% endblock title %}

{% block css %}
	{{ block.super }}
	<link rel="stylesheet" href="{% static "css/activity_stream.css" %}" />
{% endblock css %}

{% block content %}

			{% if request.user == user %}
	<a class="btn btn-default" id="profile_edit" href="{% url 'user_profile:edit_profile' username=user.username %}"><span class="glyphicon glyphicon-pencil"></span> Edit Profile</a>
	<a class="btn btn-default" id="profile_logout" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
		{% endif %}
	<h1 class="page-header">
	{{ user }}
	{% if user.get_full_name and user.get_full_name.strip %}
		<small>{{ user.username }}</small>
	{% endif %}
			<img class="img-rounded" src="{{user.avatar.url}}" alt="{% trans "Avatar" %}" width=100 />
	</h1>

	{% if request.user == user %}
		<h2>{% trans "Notification properties" %}</h2>
		<div id='notificationprops'>
			{% for uproj in user.get_projects %}
				<p>
				<button id="notibtn_{{uproj.name_short}}" class="btn btn-primary" data-toggle="collapse" data-target="#collapse_{{uproj.name_short}}">{% trans "Project" %} &quot;{{ uproj.name }}&quot;</button>
				<div class="collapse{% if nocollapse == uproj.name_short %} in{% endif %}" id="collapse_{{uproj.name_short}}">
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th>{% trans "Notification type" %}</th>
								<th>{% trans "By Mail" %}</th>
							</tr>
						</thead>
						<tbody>
							{% for noti in possible_notis %}
								<tr>
									<td>{{noti.1}}</td>
									<td>
										<form name='toggle_{{uproj.name_short}}_{{noti.0}}' method="post" action="{% url 'user_profile:toggle_notification' username=user.username %}">{% csrf_token %}
											<input type="hidden" name="shn_p" value="{{uproj.name_short}}">
											<input type="hidden" name="notiway" value="mail">
											<input type="hidden" name="notitype" value="{{noti.0}}">
											{% if noti.0 in notify_mail|get_dict_item:uproj.name_short %}
												<input type="hidden" name="enabled" value="0">
												<button id="notisend_{{uproj.name_short}}_{{noti.0}}" type="submit" class="btn btn-link btn-move"><span class="glyphicon glyphicon-ok green"></span></button>
											{% else %}
												<input type="hidden" name="enabled" value="1">
												<button id="notisend_{{uproj.name_short}}_{{noti.0}}" type="submit" class="btn btn-link btn-move"><span class="glyphicon glyphicon-remove red"></span></button>
											{% endif %}
										</form>
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				</p>
			{% endfor %}
		</div>
	{% endif %}

	<h2>{% trans "Activity" %}</h2>
	<div style="margin-bottom:15px">
		<a class="btn btn-default {% if not chart_type == 'actions' %}active{% endif %}" id="show_timelogs" href="{% url 'user_profile:user_profile_page' username=user.username %}?data=timelogs">Timelogs</a>
		<a class="btn btn-default {% if chart_type == 'actions' %}active{% endif %}" id="show_actions" href="{% url 'user_profile:user_profile_page' username=user.username %}?data=actions">Actions</a>
	</div>
<div id="cal-heatmap"></div>
<div id="onClick-placeholder" class="cal-heatmap"></div>
{% if request.user == user %}
<script>draw_activity_heatmap("{{user.username}}", true, "{{chart_type}}")</script>
{% elif user.show_activity_to_other_users %}
<script>draw_activity_heatmap("{{user.username}}", false, "{{chart_type}}")</script>
{% endif %}
{% block extra_script %}
<script src="{% static "js/graphs/d3.v3.min.js" %}"></script>
<script src="{% static "js/cal-heatmap.min.js" %}"></script>
<script src="{% static "js/graphs/draw_activity_heatmap.js" %}"></script>
<link rel="stylesheet" href="{% static "css/cal-heatmap.css" %}"/>
{% endblock extra_script %}
	{% if request.user.username != user.username %}
		{% if sharedprojects.all %}
			<div class="panel panel-default">
				<div class="panel-heading"> {% trans "Shared projects" %} </div>
				<div class="panel-body">
					{% for project in sharedprojects.all %}
						<div class="row">
							<div class="col-xs-2">
								<a style="vertical-align: middle" href="{% url 'project:detail' project=project.name_short %}">{{ project.name_short }}</a>
							</div>
							<div class="col-xs-4">
								<span>{{ project.name }}</span>
							</div>
							<div class="col-xs-4">
								{% if user in project.manager.all %}
									{% trans "Manager and developer" %}
								{% else %}
									{% trans "Developer" %}
								{% endif %}
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		{% endif %}
	{% endif %}

	{% if request.user.username != user.username %}
		{% if sharedissues.not_archived %}
			<div class="panel panel-default">
				<div class="panel-heading">
					{% trans "Shared issues" %}
				</div>
				<div class="panel-body">
					{% for issue in sharedissues.not_archived %}
						<div class="row">
							<div class="col-xs-2">
								<a href="{% url 'issue:detail' project=issue.project.name_short sqn_i=issue.number %}">{{ issue.get_ticket_identifier }}</a>
							</div>
							<div class="col-xs-4">
								<span>{{issue.title}}</span>
							</div>
							<div class="col-xs-4">
								<a href="{% url 'project:detail' project=issue.project.name_short %}">{% trans "In project: " %}{{ issue.project.name_short }}</a>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		{% endif %}
	{% endif %}

	<div class="panel panel-default">
		<div class="panel-heading">
			{% trans "Activity Stream" %}
		</div>
		<ul class="list-group">
			<li class="list-group-item activity-feed">
			{% for action in page_items %}
				{% with i=forloop.counter|stringformat:"s" %}
					{% with id="id_action_"|add:i %}
						{% include "activity_stream_item.html" with action_item_id=id %}
					{% endwith %}
				{% endwith %}
			{% endfor %}
			</li>
			{% if page_items.has_next %}
				<li class ="list-group-item">
					<a href="?page={{ page_items.next_page_number }}#id_action_{{ page_items|length|add:"1" }}">{% trans "Show More" %}</a>
				</li>
			{% endif %}
		</ul>
	</div>

{% endblock content %}